# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Estandarte Blog
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Pequenas contribuições open source da Estandarte.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://estandarte.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  estandarte

# Build settings
markdown: kramdown
remote_theme: fongandrew/hydeout

theme: jekyll-theme-minimal